version: "3"
services:
  mongo1:
    container_name: mongo1
    image: mongo
    expose:
      - 27017 
      - 27018
      - 27019
    ports:
      - 30001:27017 
    restart: always
    command: mongod --replSet "rs0" --bind_ip localhost,mongo1 --port 27017 
  mongo2:
    container_name: mongo2
    image: mongo
    expose:
      - 27017 
      - 27018
      - 27019
    ports:
      - 30002:27017
    restart: always
    command: mongod --replSet "rs0" --bind_ip localhost,mongo2 --port 27017
  mongo3:
    container_name: mongo3
    image: mongo
    expose:
      - 27017 
      - 27018
      - 27019
    ports:
      - 30003:27017
    restart: always
    command: mongod --replSet "rs0" --bind_ip localhost,mongo3 --port 27017

  mongoinit:
    image: mongo
    # this container will exit after executing the command
    restart: "no"
    depends_on:
      - mongo1
      - mongo2
      - mongo3
    command: >
      mongosh --host mongo1:27017 --eval '
      config = {
      _id : "rs0",
      "members" : [
        {
          _id : 0,
          host : "mongo1:27017"
        },
        {
          _id : 1,
          host : "mongo2:27017"
        },
        {
          _id : 2,
          host : "mongo3:27017"
        }
      ]
      };
      rs.initiate(config);
      '
  
  app:
    image: node
    container_name: app
    command: sleep infinity